name: Update Models Manual
on:
  workflow_dispatch

jobs:
  update-models:
    uses: supervisely-ecosystem/workflows/.github/workflows/update_models_common.yml@master
    with:
      MODELS_PATH: supervisely_integration/models.json
      FRAMEWORK: YOLO
      SERVER_ADDRESS: ${{ vars.SUPERVISELY_PROD_SERVER_ADDRESS }}
    secrets:
      API_TOKEN: ${{ secrets.SUPERVISELY_PROD_API_TOKEN }}
